/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>
*/

/**
 * This file create a theme file for the dashboard. The cosmetics for the
 * different charts are defined here.
 *
 * More information on theming can be found at
 * http://docs.fusioncharts.com/tutorial-configuring-your-chart-theme-manager.html
 */
FusionCharts.register('theme', {
  name: 'twitterTheme',
  theme: {
    base: {
      chart: {
        captionAlignment: "left",
        captionFontSize: "36",
        subCaptionFontSize: "32",
        captionFont: "Muli",
        subCaptionFont: "Muli",
        captionFontBold: "0",
        subCaptionFontBold: "0",
        lineColor: "#FFFFFF",
        lineThickness: "5",
        showValues: "0",
        showLabels: "0",
        showHoverEffect: "1",
        showaxislines: "1",
        bgAlpha: "0",
        canvasBgAlpha: "0",
        showCanvasBorder: "0",
        showBorder: "0",
        divLineAlpha: "0",
        alternateHGridAlpha: "0",
        showLabels: "1",
        labelStep: "10",
        showAnchors: "0",
        showAxisLines: "0",
        baseFontSize: "12",
        baseFontColor: "#fff",
        toolTipPadding: "7",
        toolTipBorderColor: "#DCDCDC",
        toolTipBorderThickness: "0",
        toolTipBorderRadius: "2",
        showShadow: "0",
        toolTipBgColor: "#153957",
        toolTipBgAlpha: "90",
        toolTipColor: "#FFFFFF",
        animation: "1"
      }
    },
    line: {
      chart: {
        captionAlignment: "left",
        captionFontSize: "36",
        subCaptionFontSize: "32",
        captionFont: "Muli",
        subCaptionFont: "Muli",
        captionFontBold: "0",
        subCaptionFontBold: "0",
        lineColor: "#FFFFFF",
        lineThickness: "5",
        showValues: "0",
        showLabels: "0",
        showHoverEffect: "1",
        showaxislines: "0",
        bgAlpha: "0",
        canvasBgAlpha: "0",
        showCanvasBorder: "0",
        showBorder: "0",
        divLineAlpha: "0",
        alternateHGridAlpha: "0",
        showLabels: "1",
        labelStep: "10",
        showAnchors: "0",
        showAxisLines: "0",
        baseFontSize: "12",
        baseFontColor: "#fff",
        toolTipPadding: "7",
        toolTipBorderColor: "#DCDCDC",
        toolTipBorderThickness: "0",
        toolTipBorderRadius: "2",
        showShadow: "0",
        toolTipBgColor: "#153957",
        toolTipBgAlpha: "90",
        toolTipColor: "#FFFFFF",
        animation: "1"
      },

    },
    sparkline: {
      chart: {
        showLabels: "0",
        canvasBorder: "0",
        chartLeftMargin: "0",
        chartRightMargin: "0",
        bgAlpha: "0",
        lineColor: "#FFFFFF",
        lineThickness: "5",
        showValues: "0",
        showHoverEffect: "1",
        bgAlpha: "0",
        canvasBgAlpha: "0",
        showCanvasBorder: "0",
        showBorder: "0",
        divLineAlpha: "0",
        alternateHGridAlpha: "0",
        showXAxisLine: "0",
        showYAxisLine: "0",
        baseFontSize: "12",
        baseFontColor: "#fff",
        showBorder: "0",
        lineThickness: "4",
        showValues: "0",
        showHighLowValue: "0",
        borderAlpha: "0",
        showBorder: "0",
        toolTipPadding: "7",
        toolTipBorderColor: "#DCDCDC",
        toolTipBorderThickness: "0",
        toolTipBorderRadius: "2",
        showShadow: "0",
        toolTipBgColor: "#153957",
        toolTipBgAlpha: "90",
        toolTipColor: "#FFFFFF",
        showOpenValue: "0",
        showCloseValue: "0"

      }
    },
    doughnut2d: {
      chart: {
        showLabels: "1",
        use3DLighting: "0",
        showValues: "1",
        borderAlpha: "0",
        startingAngle: "30",
        decimals: "0",
        canvasBorder: "0",
        doughnutRadius: "80",
        pieRadius: "90",
        enableSmartLabels: "0",
        showPercentValues: "1",
        chartLeftMargin: "0",
        chartRightMargin: "0",
        manageLabelOverflow: "1",
        labelDistance: "2",
        captionAlignment: "left",
        chartTopMargin: "0",
        captionAlignment: "left",
        captionFontSize: "30",
        subCaptionFontSize: "26",
        captionFont: "Muli",
        subCaptionFont: "Muli",
        captionFontBold: "0",
        subCaptionFontBold: "0",
        lineColor: "#FFFFFF",
        lineThickness: "5",
        showHoverEffect: "1",
        bgAlpha: "0",
        canvasBgAlpha: "0",
        showCanvasBorder: "0",
        showBorder: "0",
        divLineAlpha: "0",
        alternateHGridAlpha: "0",
        baseFontSize: "12",
        baseFontColor: "#fff",
        toolTipPadding: "7",
        toolTipBorderColor: "#DCDCDC",
        toolTipBorderThickness: "0",
        toolTipBorderRadius: "2",
        showShadow: "0",
        toolTipBgColor: "#153957",
        toolTipBgAlpha: "90",
        toolTipColor: "#FFFFFF",
        useDataPlotColorForLabels: "1",
        manageLabelOverflow: "1",
        startingAngle: "45",
        enableRotation: "0",
        labelDistance: "0"

      }
    },
    worldwithcountries: {
      chart: {

        animation: "0",
        showbevel: "0",
        usehovercolor: "0",
        canvasbordercolor: "FFFFFF",
        bordercolor: "FFFFFF",
        showlegend: "1",
        showshadow: "0",
        entityFillColor: "#A8A8A8",
        captionAlignment: "middle",
        captionFontColor: "#3C92C9",
        captionFontSize: "32",
        subCaptionFontSize: "28",
        captionFont: "Muli",
        subCaptionFont: "Muli",
        captionFontBold: "0",
        subCaptionFontBold: "0",
        showLabels: "0",
        toolTipPadding: "7",
        toolTipBorderColor: "#DCDCDC",
        toolTipBorderThickness: "0",
        toolTipBorderRadius: "2",
        showShadow: "0",
        toolTipBgColor: "#153957",
        toolTipBgAlpha: "90",
        toolTipColor: "#FFFFFF",
        baseFontSize: "12",
      }
    },
    geo: {
      chart: {
        showshadow: '0',
        showlabels: '0',
        showmarkerlabels: '0',
        bordercolor: 'FFFFFF',
        basefont: 'Verdana',
        basefontsize: '10',
        canvasBorderAlpha: '0',
        showBorder: '1',
        baseFontColor: '#000000',
        fontBold: '1',
        baseFontSize: '30',
        useSNameInLabels: '0',
        fillColor: '#EBEBEB',
        showLegend: '0',
        legendShadow: '0',
        legendBorderThickness: '0',
        legendScaleLineThickness: '0',
        legendPointerBorderThickness: '0',
        legendPointerHeight: '0',
        legendPointerWidth: '0',
        legendBorderAlpha: '0',
        legendBgAlpha: '0',
        showToolTip: '1',
        numberSuffix: '%'
      }
    }
  }
});
